name: "deploy"

on:
  workflow_run:
    workflows:
      - "Ci"
    branches:
      - feature/1
    types:
      - completed
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
